import streamlit as st
import google.generativeai as genai
from datetime import datetime
from fpdf import FPDF
import textwrap

# --- DEINE LINKS (HIER ANPASSEN!) ---
YOUTUBE_VIDEO_URL = "https://www.youtube.com/@WorldMusicChannel" # Dein Kanal
HOMEPAGE_URL = "https://www.worldmusicchannel.com"
SHOP_LINKS = {
    "wav": "https://www.worldmusicchannel.com/shop/hd-wav",
    "mp3": "https://www.worldmusicchannel.com/shop/mp3",
    "video": "https://www.worldmusicchannel.com/shop/video",
    "merch": "https://www.worldmusicchannel.com/shop/merch"
}

# --- PDF GENERATOR FUNKTION ---
def create_pdf(interpretation_text, code_name):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Header
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "WMC Artist Portal - Official Interpretation", ln=True, align='C')
    pdf.ln(10)
    
    # Sub-Header
    pdf.set_font("Arial", "I", 12)
    pdf.cell(0, 10, f"Quest: {code_name}", ln=True, align='L')
    pdf.line(10, 30, 200, 30) # Linie ziehen
    pdf.ln(10)
    
    # Body Text (Interpretation)
    pdf.set_font("Arial", size=12)
    # Text bereinigen (Emojis entfernen, da PDF diese oft nicht mag)
    safe_text = interpretation_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, safe_text)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by World Music Channel AI Muse", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- CONFIGURATION ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("Error: API Key not found.")
    st.stop()

QUEST_END_DATE = datetime(2026, 2, 15) 
MODELS_CONFIG = {
    "LYA-SESSION-2": {
        "persona": (
            "You are the digital muse of Lya Nights. Interpret the lyrics deeply and poetically. "
            "IMPORTANT: Answer in the same language as the lyrics."
        ),
        "name": "Lya Nights - City Lights"
    }
}

# --- UI DESIGN ---
st.set_page_config(page_title="WMC Artist Portal", page_icon="🎵")

# Logo Integration
try:
    st.image("logo.png", width=200) 
except:
    st.markdown("## World Music Channel 🎵")

st.subheader("Official Artist Portal")

# --- APP LOGIC ---
if datetime.now() > QUEST_END_DATE:
    st.error("🛑 Quest ended.")
else:
    # Intro Story
    st.markdown("""
    **Unlock the Soul of the Music.** Paste your favorite lyrics below. Our AI Muse will reveal their hidden meaning.
    """)

    q_code = st.text_input("Enter Quest Code:").upper()
    
    if q_code in MODELS_CONFIG:
        st.success(f"✅ Connected: {MODELS_CONFIG[q_code]['name']}")
        
        user_lyrics = st.text_area("Paste lyrics (max 300 chars):", max_chars=300, height=100)
        
        if st.button("✨ Reveal Interpretation"):
            if len(user_lyrics) > 5:
                with st.spinner("Connecting to the Muse..."):
                    try:
                        model = genai.GenerativeModel('models/gemini-2.0-flash', 
                                                      system_instruction=MODELS_CONFIG[q_code]['persona'])
                        response = model.generate_content(user_lyrics)
                        
                        # --- 1. SCHÖNE TEXTAUSGABE (Kein Scrollen!) ---
                        st.markdown("---")
                        st.markdown("### 🔮 Your Personal Interpretation")
                        
                        # Wir nutzen eine Info-Box, die den Text schön umbricht
                        st.info(response.text)
                        
                        # --- 2. PDF DOWNLOAD ---
                        pdf_bytes = create_pdf(response.text, MODELS_CONFIG[q_code]['name'])
                        st.download_button(
                            label="📄 Download as Official WMC-PDF",
                            data=pdf_bytes,
                            file_name="WMC_Interpretation.pdf",
                            mime="application/pdf"
                        )
                        
                        # Copy Help
                        st.caption("👇 Click inside to copy for YouTube:")
                        st.text_area("Copy Text", value=response.text, height=100, label_visibility="collapsed")
                        st.link_button("Go to YouTube to Comment 🎬", YOUTUBE_VIDEO_URL)
                        
                    except Exception as e:
                        st.error(f"Error: {e}")
    elif q_code != "":
        st.warning("Invalid Code.")

# --- 3. DER NEUE MEGA-SHOP (4 ANGEBOTE) ---
st.markdown("---")
st.markdown("### 🛍️ Exclusive WMC Collection")

# 4 Spalten für deine Produkte
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.markdown("#### 🎧 HD WAV")
    st.caption("Audiophile Quality")
    st.link_button("Get WAV", SHOP_LINKS["wav"])

with col2:
    st.markdown("#### 🎵 MP3")
    st.caption("Universal Format")
    st.link_button("Get MP3", SHOP_LINKS["mp3"])

with col3:
    st.markdown("#### 🎬 Video")
    st.caption("Official Cut")
    st.link_button("Watch/Buy", SHOP_LINKS["video"])

with col4:
    st.markdown("#### 👕 Merch")
    st.caption("Shirt & Mug")
    st.link_button("Go to Shop", SHOP_LINKS["merch"])
