import streamlit as st
import requests
import json
from datetime import datetime
from fpdf import FPDF

# --- CONFIGURATION & LINKS ---
YOUTUBE_VIDEO_URL = "https://www.youtube.com/@WorldMusicChannel-y3s" 
HOMEPAGE_URL = "https://www.worldmusicchannel.com"
SHOP_LINKS = {
    "wav": "https://www.worldmusicchannel.com/shop/hd-wav",
    "mp3": "https://www.worldmusicchannel.com/shop/mp3",
    "video": "https://www.worldmusicchannel.com/shop/video",
    "merch": "https://www.worldmusicchannel.com/shop/merch"
}

QUEST_END_DATE = datetime(2026, 2, 15) 
MODELS_CONFIG = {
    "LYA-SESSION-2": {
        "persona": (
            "You are the digital muse of Lya Nights. Interpret the lyrics deeply but concisely. "
            "IMPORTANT RULES: "
            "1. Answer in the same language as the lyrics. "
            "2. KEEP IT SHORT: Maximum 150-200 words. "
            "3. Focus on the core meaning and urban poetry."
        ),
        "name": "Lya Nights - City Lights"
    }
}

# --- PDF GENERATOR ---
class WMCPDF(FPDF):
    def header(self):
        try:
            self.image('logo.png', 10, 10, 30)
        except:
            pass 
        self.set_y(15)
        self.set_font('Arial', 'B', 16)
        self.cell(0, 8, 'World Music Channel', 0, 1, 'R')
        self.set_font('Arial', 'BI', 12)
        self.set_text_color(50, 50, 50)
        self.cell(0, 6, '"Feel the Music"', 0, 1, 'R')
        self.set_font('Arial', '', 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Official Artist Portal', 0, 1, 'R')
        self.ln(8)
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(0, 0, 255)
        self.cell(0, 5, '>> Click here to visit our YouTube Channel', 0, 1, 'C', link=YOUTUBE_VIDEO_URL)
        self.set_font('Arial', '', 9)
        self.set_text_color(0, 0, 0)
        self.cell(0, 5, f'URL: {YOUTUBE_VIDEO_URL}', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 5, f'Page {self.page_no()} - Generated by WMC AI Muse', 0, 0, 'C')

def create_corporate_pdf(interpretation_text, code_name):
    pdf = WMCPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0)
    pdf.cell(0, 10, f"Interpretation: {code_name}", ln=True, align='L')
    pdf.ln(5)
    pdf.set_font("Arial", size=11)
    # Zeichenbereinigung für PDF
    safe_text = interpretation_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, safe_text)
    return pdf.output(dest='S').encode('latin-1')

# --- ENGINE (DIREKT-VERBINDUNG) ---
def get_gemini_response(prompt, api_key):
    # FIX: Wir nutzen jetzt explizit gemini-1.5-flash (modern & schnell)
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    headers = {'Content-Type': 'application/json'}
    data = {
        "contents": [{"parts": [{"text": prompt}]}]
    }
    
    try:
        response = requests.post(url, headers=headers, json=data)
        if response.status_code == 200:
            return response.json()['candidates'][0]['content']['parts'][0]['text']
        else:
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Connection Error: {str(e)}"

# --- UI DESIGN ---
st.set_page_config(page_title="WMC Artist Portal", page_icon="🎵", layout="centered")

# Header Layout: Text Links, Bild Rechts (3:1 Verhältnis)
col_text, col_img = st.columns([3, 1])

with col_text:
    st.title("World Music Channel")
    st.markdown("### *Feel the Music*") 
    st.caption("Official Artist Portal & Fan Experience")

with col_img:
    try:
        st.image("logo.png", use_container_width=True)
    except:
        st.header("🎵") 

st.markdown("---")

# --- APP LOGIC ---
if datetime.now() > QUEST_END_DATE:
    st.error("🛑 Quest ended.")
    st.link_button("Go to Homepage", HOMEPAGE_URL)
else:
    st.markdown("""
    ### ✨ Unlock the Soul of the Music
    **Paste your favorite lyrics below.** Our AI Muse will reveal their hidden meaning.
    """)

    q_code = st.text_input("Enter Quest Code:").upper()
    
    if q_code in MODELS_CONFIG:
        st.success(f"✅ Connected: {MODELS_CONFIG[q_code]['name']}")
        
        user_lyrics = st.text_area("Paste lyrics (max 150 chars):", max_chars=150, height=100)
        
        if st.button("✨ Reveal Interpretation", type="primary"):
            if len(user_lyrics) > 5:
                # API Check
                if "GEMINI_API_KEY" not in st.secrets:
                    st.error("⚠️ API Key fehlt in den Secrets!")
                else:
                    with st.spinner("Connecting to Muse..."):
                        # Prompt
                        full_prompt = MODELS_CONFIG[q_code]['persona'] + "\n\nLYRICS:\n" + user_lyrics
                        
                        # Abruf
                        result_text = get_gemini_response(full_prompt, st.secrets["GEMINI_API_KEY"])
                        
                        if "Error:" in result_text:
                            st.error(f"Ein Fehler ist aufgetreten: {result_text}")
                        else:
                            st.markdown("---")
                            st.markdown("### 🔮 Your Personal Interpretation")
                            st.info(result_text)
                            
                            # PDF Download
                            pdf_bytes = create_corporate_pdf(result_text, MODELS_CONFIG[q_code]['name'])
                            col_dl, col_copy = st.columns(2)
                            with col_dl:
                                st.download_button(
                                    label="📄 Download PDF",
                                    data=pdf_bytes,
                                    file_name="WMC_Interpretation.pdf",
                                    mime="application/pdf"
                                )
                            with col_copy:
                                st.link_button("Go to YouTube 🎬", YOUTUBE_VIDEO_URL)
                                
    elif q_code != "":
        st.warning("Invalid Code.")

# --- SHOP FOOTER ---
st.markdown("---")
st.markdown("### 🛍️ Exclusive WMC Collection")

# Buttons sauber nebeneinander
c1, c2, c3, c4 = st.columns(4)
with c1:
    st.link_button("🎧 HD WAV", SHOP_LINKS["wav"])
with c2:
    st.link_button("🎵 MP3", SHOP_LINKS["mp3"])
with c3:
    st.link_button("🎬 Video", SHOP_LINKS["video"])
with c4:
    st.link_button("👕 Merch", SHOP_LINKS["merch"])
