import streamlit as st
import google.generativeai as genai
from datetime import datetime
from fpdf import FPDF

# --- DEINE ECHTEN LINKS ---
YOUTUBE_VIDEO_URL = "https://www.youtube.com/@WorldMusicChannel-y3s" 
HOMEPAGE_URL = "https://www.worldmusicchannel.com"
SHOP_LINKS = {
    "wav": "https://www.worldmusicchannel.com/shop/hd-wav",
    "mp3": "https://www.worldmusicchannel.com/shop/mp3",
    "video": "https://www.worldmusicchannel.com/shop/video",
    "merch": "https://www.worldmusicchannel.com/shop/merch"
}

# --- PDF GENERATOR ---
class WMCPDF(FPDF):
    def header(self):
        try:
            self.image('logo.png', 10, 10, 30)
        except:
            pass 
        
        self.set_y(15)
        self.set_font('Arial', 'B', 16)
        self.cell(0, 8, 'World Music Channel', 0, 1, 'R')
        
        self.set_font('Arial', 'BI', 12)
        self.set_text_color(50, 50, 50)
        self.cell(0, 6, '"Feel the Music"', 0, 1, 'R')
        
        self.set_font('Arial', '', 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Official Artist Portal', 0, 1, 'R')
        
        self.ln(8)
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        
        # WICHTIG: ">>" statt Play-Symbol verhindert PDF-Absturz!
        self.set_font('Arial', 'B', 10)
        self.set_text_color(0, 0, 255)
        self.cell(0, 5, '>> Click here to visit our YouTube Channel', 0, 1, 'C', link=YOUTUBE_VIDEO_URL)
        
        self.set_font('Arial', '', 9)
        self.set_text_color(0, 0, 0)
        self.cell(0, 5, f'URL: {YOUTUBE_VIDEO_URL}', 0, 1, 'C')
        
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 5, f'Page {self.page_no()} - Generated by WMC AI Muse', 0, 0, 'C')

def create_corporate_pdf(interpretation_text, code_name):
    pdf = WMCPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0)
    pdf.cell(0, 10, f"Interpretation: {code_name}", ln=True, align='L')
    pdf.ln(5)
    
    pdf.set_font("Arial", size=11)
    # Filtert problematische Zeichen heraus
    safe_text = interpretation_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, safe_text)
    
    return pdf.output(dest='S').encode('latin-1')

# --- CONFIGURATION ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("Error: API Key not found.")
    st.stop()

QUEST_END_DATE = datetime(2026, 2, 15) 
MODELS_CONFIG = {
    "LYA-SESSION-2": {
        "persona": (
            "You are the digital muse of Lya Nights. Interpret the lyrics deeply but concisely. "
            "IMPORTANT RULES: "
            "1. Answer in the same language as the lyrics. "
            "2. KEEP IT SHORT: Maximum 150-200 words (about half a page). "
            "3. Focus on the core meaning and urban poetry."
        ),
        "name": "Lya Nights - City Lights"
    }
}

# --- UI DESIGN ---
st.set_page_config(page_title="WMC Artist Portal", page_icon="🎵")

col_logo, col_info = st.columns([1, 2])
with col_logo:
    try:
        st.image("logo.png", use_container_width=True)
    except:
        st.header("🎵") 

with col_info:
    st.title("World Music Channel")
    st.markdown("### *Feel the Music*") 
    st.caption("Official Artist Portal")
    try:
        st.image("album.jpg", width=300, caption="New Album Out Now!")
    except:
        st.info("New Album 'City Lights' - Available in Shop!")

st.markdown("---")

# --- APP LOGIC ---
if datetime.now() > QUEST_END_DATE:
    st.error("🛑 Quest ended.")
    st.link_button("Go to Homepage", HOMEPAGE_URL)
else:
    st.markdown("""
    ### ✨ Unlock the Soul of the Music
    **Paste your favorite lyrics below.** Our AI Muse will reveal their hidden meaning.
    """)

    q_code = st.text_input("Enter Quest Code:").upper()
    
    if q_code in MODELS_CONFIG:
        st.success(f"✅ Connected: {MODELS_CONFIG[q_code]['name']}")
        
        user_lyrics = st.text_area("Paste lyrics (max 150 chars):", max_chars=150, height=100)
        
        if st.button("✨ Reveal Interpretation"):
            if len(user_lyrics) > 5:
                with st.spinner("Processing..."):
                    try:
                        # Wir nutzen jetzt das stabile Flash-Modell:
                        model = genai.GenerativeModel('gemini-1.5-flash', 
                                                      system_instruction=MODELS_CONFIG[q_code]['persona'])
                        response = model.generate_content(user_lyrics)
                        
                        st.markdown("---")
                        st.markdown("### 🔮 Your Personal Interpretation")
                        st.info(response.text)
                        
                        pdf_bytes = create_corporate_pdf(response.text, MODELS_CONFIG[q_code]['name'])
                        st.download_button(
                            label="📄 Download Official PDF (WMC Design)",
                            data=pdf_bytes,
                            file_name="WMC_Interpretation.pdf",
                            mime="application/pdf"
                        )
                        
                        st.caption("👇 Click inside to copy for YouTube:")
                        st.text_area("Copy Text", value=response.text, height=100, label_visibility="collapsed")
                        st.link_button("Go to YouTube to Comment 🎬", YOUTUBE_VIDEO_URL)
                        
                    except Exception as e:
                        # Detaillierte Fehlermeldung falls etwas schiefgeht
                        st.error(f"Error ({type(e).__name__}): {e}")
    elif q_code != "":
        st.warning("Invalid Code.")

# --- SHOP & FOOTER ---
st.markdown("---")
st.markdown("### 🛍️ Exclusive WMC Collection")
c1, c2, c3, c4 = st.columns(4)
with c1:
    st.markdown("**🎧 HD WAV**")
    st.caption("Audiophile Quality")
    st.link_button("Go to Shop", SHOP_LINKS["wav"])
with c2:
    st.markdown("**🎵 MP3**")
    st.caption("Universal Format")
    st.link_button("Go to Shop", SHOP_LINKS["mp3"])
with c3:
    st.markdown("**🎬 Video**")
    st.caption("Official Cut")
    st.link_button("Go to Shop", SHOP_LINKS["video"])
with c4:
    st.markdown("**👕 Merch**")
    st.caption("Shirt & Mug")
    st.link_button("Go to Shop", SHOP_LINKS["merch"])

st.markdown("---")
col_l, col_center, col_r = st.columns([1, 2, 1])
with col_center:
    st.link_button("🌐 Visit Official Homepage (World Music Channel)", HOMEPAGE_URL, use_container_width=True)
